# Generated by Django 5.1.1 on 2024-09-27 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(default='pbkdf2_sha256$870000$Y9chbqb0fdiKUWT66PEQYg$ljWp9epb4FCGJizq96OvBeqoDYv7e1h21LOzapatcAQ=', max_length=128),
        ),
        migrations.RenameModel(
            old_name='SolariGroups',
            new_name='SolariGroup',
        ),
        migrations.CreateModel(
            name='SolariGroupChatSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solari.solarigroup')),
            ],
        ),
        migrations.RenameModel(
            old_name='SolariSubGroups',
            new_name='SolariSubGroup',
        ),
        migrations.CreateModel(
            name='SolariSubGroupChatSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solari.solarisubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SolariGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('text', 'Text'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chatspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solari.solarisubgroupchatspace')),
            ],
            options={
                'indexes': [models.Index(fields=['chatspace', 'created'], name='solari_sola_chatspa_cab8d8_idx')],
            },
        ),
    ]
