# Generated by Django 5.1.1 on 2024-09-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solari', '0002_alter_user_pin_rename_solarigroups_solarigroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
    ]
