# Generated by Django 5.1.1 on 2024-09-27 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solari', '0003_remove_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarigroupmessage',
            name='chatspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solari.solarigroupchatspace'),
        ),
        migrations.CreateModel(
            name='SolariSubGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('text', 'Text'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chatspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solari.solarisubgroupchatspace')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['chatspace', 'created'], name='solari_sola_chatspa_a6bda4_idx')],
            },
        ),
    ]
