# Generated by Django 5.1.1 on 2024-09-29 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solari', '0004_alter_solarigroupmessage_chatspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('text', 'Text'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solarigroup',
            options={'verbose_name_plural': 'solari_groups'},
        ),
        migrations.AddIndex(
            model_name='solarigroup',
            index=models.Index(fields=['name'], name='solari_sola_name_f19740_idx'),
        ),
        migrations.AddIndex(
            model_name='solarigroup',
            index=models.Index(fields=['id'], name='solari_sola_id_2d7828_idx'),
        ),
        migrations.AddField(
            model_name='userchatspace',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='chatspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solari.userchatspace'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
